#ifndef _CSI_CONFIG_H_
#define _CSI_CONFIG_H_
#define CONFIG_HAVE_VIC 1
#define CONFIG_SUPPORT_TSPEND 1
#define CONFIG_SEPARATE_IRQ_SP 1
#define CONFIG_ARCH_INTERRUPTSTACK 2048
#define CONFIG_SYSTICK_HZ 1000
#endif
