
#ifndef _HGIC_SYSVAR_H_
#define _HGIC_SYSVAR_H_
enum sysvar_id {
    SYSVAR_ID_LMACHOST,
    SYSVAR_ID_UMAC,
    SYSVAR_ID_UMAC_HOSTOPS,
    SYSVAR_ID_UMAC_HGLOOP_DATA,
    SYSVAR_ID_UMAC_HGLINK_DATA,
    SYSVAR_ID_UMAC_NETDEVICE,
    SYSVAR_ID_UMAC_WORKQUEUE,
    SYSVAR_ID_UMAC_WBNAT,
    SYSVAR_ID_UMAC_LOCALOPS,
    SYSVAR_ID_UMAC_S1G_CHANLIST,
    SYSVAR_ID_UMAC_WPAS_SSIDTXT,
    SYSVAR_ID_UMAC_CFG80211_CORE,
    SYSVAR_ID_UMAC_WPAS_SCANMATCH,
    SYSVAR_ID_UMAC_WPAS_GLOBAL,
    SYSVAR_ID_WIRELESS_NB,
    SYSVAR_ID_ATCMD_MGR,
    SYSVAR_ID_MAX,
};
void *sysvar_init(enum sysvar_id id, int size);
void *sysvar(enum sysvar_id id);
#endif
